// roomData.js — all room-specific content for MCM Dream planner v3

export const ROOMS = {
  "2nd Floor — Main Level": [
    { id: "living", name: "Living Room", dims: '22\'2" × 18\'1"', w: 266, h: 217, sqft: 401, floor: 2, icon: "◧" },
    { id: "dining", name: "Dining Area", dims: '16\'5" × 19\'0"', w: 197, h: 228, sqft: 312, floor: 2, icon: "◫" },
    { id: "kitchen", name: "Kitchen", dims: '17\'0" × 14\'0"', w: 204, h: 168, sqft: 238, floor: 2, icon: "⬡" },
    { id: "breakfast", name: "Breakfast Nook", dims: '9\'7" × 13\'2"', w: 115, h: 158, sqft: 126, floor: 2, icon: "◯" },
    { id: "foyer", name: "Foyer", dims: '23\'5" × 12\'1"', w: 281, h: 145, sqft: 283, floor: 2, icon: "⬢" },
    { id: "primary_bed", name: "Primary Bedroom", dims: '17\'0" × 17\'10"', w: 204, h: 214, sqft: 303, floor: 2, icon: "◈" },
    { id: "primary_bath", name: "Primary Bath", dims: '17\'0" × 8\'1"', w: 204, h: 97, sqft: 137, floor: 2, icon: "◇" },
    { id: "primary_wic", name: "Primary Closet", dims: '7\'9" × 6\'0"', w: 93, h: 72, sqft: 47, floor: 2, icon: "□" },
    { id: "laundry", name: "Laundry", dims: '6\'0" × 5\'11"', w: 72, h: 71, sqft: 36, floor: 2, icon: "○" },
    { id: "deck", name: "Deck", dims: '15\'0" × 11\'10"', w: 180, h: 142, sqft: 178, floor: 2, icon: "▽" },
    { id: "porch", name: "Porch", dims: '13\'7" × 6\'1"', w: 163, h: 73, sqft: 83, floor: 2, icon: "△" },
    { id: "garage", name: "Garage", dims: '22\'5" × 25\'9"', w: 269, h: 309, sqft: 577, floor: 2, icon: "▢" },
  ],
  "1st Floor — Lower Level": [
    { id: "family", name: "Family Room", dims: '22\'3" × 29\'6"', w: 267, h: 354, sqft: 657, floor: 1, icon: "◧" },
    { id: "rec", name: "Recreation Room", dims: '15\'5" × 20\'0"', w: 185, h: 240, sqft: 308, floor: 1, icon: "◈" },
    { id: "aakesh_office", name: "Aakesh's Office", dims: '12\'8" × 13\'7"', w: 152, h: 163, sqft: 172, floor: 1, icon: "⌘" },
    { id: "ashton_office", name: "Ashton's Office", dims: '12\'7" × 11\'10"', w: 151, h: 142, sqft: 149, floor: 1, icon: "⌘" },
    { id: "bonus", name: "Bonus Room", dims: '15\'1" × 11\'4"', w: 181, h: 136, sqft: 171, floor: 1, icon: "⬡" },
    { id: "lower_bath", name: "Lower Level Bath", dims: '9\'2" × 6\'1"', w: 110, h: 73, sqft: 56, floor: 1, icon: "○" },
    { id: "wic_aakesh", name: "Office Closet (A)", dims: '3\'5" × 3\'1"', w: 41, h: 37, sqft: 11, floor: 1, icon: "□" },
    { id: "wic_ashton", name: "Office Closet (Ash)", dims: '3\'5" × 5\'4"', w: 41, h: 64, sqft: 18, floor: 1, icon: "□" },
    { id: "storage", name: "Flex Space", dims: '32\'11" × 18\'11"', w: 395, h: 227, sqft: 623, floor: 1, icon: "⬢" },
  ]
};

// Observations based on actual listing photos
export const ROOM_OBSERVATIONS = {
  living: {
    summary: "The showpiece. Double-height stone fireplace, floor-to-ceiling windows with wooded views, vaulted ceiling with angular rooflines, and clerestory windows flooding the stone with natural light. This room has cathedral energy.",
    whatsGood: ["Stone fireplace is a world-class architectural feature", "Floor-to-ceiling windows on two walls with mature tree views", "Vaulted ceiling with clerestory windows — extraordinary natural light", "Oak window frames throughout match the house's material language", "Half-wall railing to foyer creates visual flow between spaces"],
    whatsDateOr: ["Carpet — likely hiding hardwood or subfloor worth upgrading", "Current furniture doesn't match the room's potential", "Recessed lighting is fine but a statement pendant or arc lamp would elevate"],
    verdict: "This room needs furniture and flooring, not renovation. The bones are so strong that over-designing would hurt. Let the fireplace and windows do the talking.",
    priority: "Planning",
    suggestedPalettes: ["Moody Library", "Chocolate & Cream", "Warm Walnut", "Scandinavian Light"],
  },
  dining: {
    summary: "Generous space connected to living room and kitchen. Floor-to-ceiling windows with wood frames and deck access. Currently carpeted with a modest table — this room is ready for the large hosting table you want.",
    whatsGood: ["Big windows with deck access — great natural light and indoor-outdoor flow", "Open sightline to living room creates a cohesive entertaining zone", "Existing chandelier is actually MCM-adjacent", "Room easily handles an 84–96″ table with clearance"],
    whatsDateOr: ["Carpet is the biggest issue — needs hardwood to match kitchen flow", "Existing bookshelf unit crowds the space — remove and let the room breathe", "Wall color is neutral but could take something warmer or bolder"],
    verdict: "Flooring first, then the table. Once you have hardwood continuous from kitchen through dining, the room transforms. The big table becomes the anchor.",
    priority: "Planning",
    suggestedPalettes: ["Warm Walnut", "Teak & Mustard", "Desert Modern", "Harvest Gold"],
  },
  kitchen: {
    summary: "Solid working kitchen with original oak cabinets, white laminate countertops, center island, and beautiful hardwood floors. The teal accent wall in the breakfast nook area is already a strong MCM move.",
    whatsGood: ["Hardwood floors in great condition", "Center island is functional and well-sized", "Oak lower cabinets are solid — real wood, not veneer", "Large window over sink with wooded view", "Teal accent wall is already a great MCM color", "Open flow to breakfast nook creates an expansive feel"],
    whatsDateOr: ["White laminate countertops are the most dated element", "Appliances appear original — replacement likely needed", "Beadboard backsplash is dated", "Cabinet hardware is basic — easy swap to brass or matte black"],
    verdict: "The cabinets are keepers. Hardware swap is the cheapest win. Countertops are the big decision: butcher block doubles down on MCM warmth, quartz modernizes. Appliances will need replacing but that's functional, not aesthetic.",
    priority: "Planning",
    suggestedPalettes: ["Atomic Ranch", "Coastal Teak", "Teak & Mustard", "Warm Walnut"],
  },
  breakfast: {
    summary: "Open to the kitchen with the teal accent wall and glass door to the deck. This is the casual daily eating spot and the transition zone to outdoor living.",
    whatsGood: ["Teal wall is a keeper — it works perfectly with the oak tones", "Glass door to deck creates indoor-outdoor connection", "Natural light from multiple angles", "Hardwood floors continuous with kitchen"],
    whatsDateOr: ["Current small table and chairs are staging — you'll want something with more character"],
    verdict: "Low effort needed. The teal wall and deck access do the heavy lifting. A round MCM table with 2–4 chairs and a pendant light above it completes this space.",
    priority: "Not Started",
    suggestedPalettes: ["Coastal Teak", "Atomic Ranch"],
  },
  foyer: {
    summary: "283 sq ft entry with a stunning oak craftsman door assembly, geometric transom windows, skylight, and tile flooring. The stained glass accent piece and oak railing down to the lower level make this feel like a gallery.",
    whatsGood: ["Oak front door with sidelights and geometric transom is a statement", "Skylight floods entry with natural light", "Tile floor is practical for an entry", "Visual connection to lower level via oak railing", "283 sq ft is a room, not just a hallway"],
    whatsDateOr: ["Tile pattern is dated — could be replaced or covered with a statement rug/runner", "Recessed lighting could be supplemented with a statement pendant", "Walls are blank canvas — one piece of art or a MCM console would anchor it"],
    verdict: "Needs a console table, a statement pendant, and one bold art piece. That's it. The architecture already makes the first impression.",
    priority: "Not Started",
    suggestedPalettes: ["Warm Walnut", "Chocolate & Cream", "Scandinavian Light"],
  },
  primary_bed: {
    summary: "303 sq ft near-square room with white walls, carpet, large windows/sliding door to a patio with wooded views, and access to the primary bath and walk-in closet. Clean canvas with great natural light.",
    whatsGood: ["Great proportions — near-perfect square", "Sliding door/large window to private wooded patio", "Excellent natural light", "En-suite bath and walk-in closet access", "White walls are a blank canvas for any palette"],
    whatsDateOr: ["Carpet throughout — hardwood would warm and modernize", "Current lighting is basic recessed cans and wall sconces", "No architectural features to build around — needs furniture to create character"],
    verdict: "King bed centered on the wall opposite the windows, flanked by slim nightstands. The sliding door view is your headboard wall's competition — orient the bed so you wake up looking at trees. Flooring and a platform bed frame set the tone for everything else.",
    priority: "Planning",
    suggestedPalettes: ["Chocolate & Cream", "Scandinavian Light", "Nordic Frost", "Desert Modern"],
  },
  primary_bath: {
    summary: "The silver/grey textured wallpaper is bold but not cheap. Soaking tub under a massive window overlooking trees. Dual sinks with vanity station. Grey tile floor.",
    whatsGood: ["Soaking tub with tree view window is legitimately luxurious", "Dual sinks are practical", "Vanity station between sinks is a nice touch", "Grey tile floor is in good condition", "Overall size is generous at 137 sq ft"],
    whatsDateOr: ["Silver textured wallpaper is polarizing — love it or strip it", "Crystal ceiling fixture doesn't match MCM aesthetic", "White cabinet style is fine but generic"],
    verdict: "Livable as-is. Low priority for renovation. If you do anything: swap the ceiling fixture for something MCM and decide on the wallpaper. The tub + window combo is the star — don't touch it.",
    priority: "Not Started",
    suggestedPalettes: ["Nordic Frost", "Scandinavian Light"],
  },
  primary_wic: {
    summary: "Modest walk-in at 47 sq ft. With a king bed and two wardrobes worth of clothing, a closet system is essential, not optional.",
    whatsGood: ["Dedicated walk-in is better than a reach-in"],
    whatsDateOr: ["At 7'9″ × 6'0″, every inch needs to be planned", "Likely needs a closet organizer system (Elfa, IKEA PAX, or custom)"],
    verdict: "Measure on move-in day and order a closet system immediately. This is one of the first functional purchases. Could also house a Litter-Robot if you add ventilation.",
    priority: "Planning",
    suggestedPalettes: [],
  },
  laundry: {
    summary: "Small utility room on the main level. Primary candidate for Litter-Robot placement — it has ventilation, is near the primary suite, and is a utility space visitors won't see.",
    whatsGood: ["Main level location for convenience", "Existing ventilation", "Hidden from guest view"],
    whatsDateOr: ["36 sq ft is tight — fits washer/dryer and maybe 1–2 Litter-Robots"],
    verdict: "Functional space. Measure for Litter-Robot placement on day one. A shelf above the washer/dryer maximizes vertical storage.",
    priority: "Not Started",
    suggestedPalettes: [],
  },
  deck: {
    summary: "Upper level deck with wooded views, accessible from the kitchen/breakfast nook area. This is where the Blackstone goes — close to the kitchen for food prep flow.",
    whatsGood: ["Direct kitchen access for cooking flow", "Wooded privacy once trees leaf out", "Stairs down to lower patio give multi-level outdoor access", "Existing railing in decent shape"],
    whatsDateOr: ["Wood railing and decking need condition assessment — check for rot", "Current layout is bare — needs a proper cooking station zone", "No overhead cover for weather protection"],
    verdict: "Blackstone griddle setup is the priority: griddle + prep cart + tool storage. Position away from the railing so grease splatter doesn't hit seating. The stairs down to the patio create a natural flow for entertaining on both levels.",
    priority: "Planning",
    suggestedPalettes: [],
  },
  porch: {
    summary: "Front entry porch — the first impression. Currently understated.",
    whatsGood: ["Clean lines matching the house's contemporary architecture"],
    whatsDateOr: ["No statement elements — house numbers, lighting, planters would all help", "Current approach is functional but not memorable"],
    verdict: "MCM house numbers, a statement exterior light fixture, and clean planters. 30 minutes of work for a completely different arrival experience.",
    priority: "Not Started",
    suggestedPalettes: [],
  },
  garage: {
    summary: "Large 2+ car garage. The wood garage door matches the house's siding — a nice architectural detail.",
    whatsGood: ["Generous at 577 sq ft", "Wood door matches house aesthetic", "Integrated with house design, not an afterthought"],
    whatsDateOr: ["Likely needs organization systems — wall storage, shelving"],
    verdict: "Low priority for design. Functional organization when you move in — wall-mounted storage, shelving, workbench area.",
    priority: "Not Started",
    suggestedPalettes: [],
  },
  family: {
    summary: "657 sq ft with a second stone fireplace, walkout glass doors to the patio, the stunning curved oak stair railing with pendant track lighting, and the bar area. Way more natural light than expected for a lower level — this is a true walkout.",
    whatsGood: ["Second stone fireplace echoes the living room — both floors anchored by fire", "Walkout glass doors with full natural light", "Curved oak railing and pendant lights at the stair landing — gorgeous architectural feature", "Bar area near the railing creates a natural social zone", "Massive square footage for zoning multiple activity areas", "Tile-to-carpet transition at stairs shows the space gets real traffic"],
    whatsDateOr: ["Carpet throughout — flooring upgrade would transform it", "657 sq ft needs intentional zoning or it feels cavernous", "Current furniture doesn't match the space's potential"],
    verdict: "This is your entertainment HQ. Zone it: media area around the fireplace wall, bar/social zone near the curved railing, and flexible seating in between. The bar area is basically a built-in feature — lean into it with a proper MCM bar cabinet and stools.",
    priority: "Planning",
    suggestedPalettes: ["Warm Walnut", "Moody Library", "Eames Era", "Chocolate & Cream"],
  },
  rec: {
    summary: "308 sq ft adjacent to the family room. With the family room handling media and socializing, this room is free to be purely recreational — game room, lounge, or hobby space.",
    whatsGood: ["Good separation from the family room while still being adjacent", "Enough space for a pool table, game table, or dedicated hobby"],
    whatsDateOr: ["No photos available — will need in-person assessment"],
    verdict: "Define its purpose after living in the house for a month. Don't rush this one. The family room is the priority on this level.",
    priority: "Not Started",
    suggestedPalettes: ["Eames Era", "Atomic Ranch", "Sunset Strip"],
  },
  aakesh_office: {
    summary: "172 sq ft, light grey walls, carpet, single window with a view. Currently a blank room with oak baseboard trim. Clean canvas for your command center — desk + gaming + convertible couch for occasional guests.",
    whatsGood: ["Clean blank slate — no dated features to work around", "Window on the short wall means desk on long wall avoids monitor glare", "Oak baseboard trim matches the house", "Decent natural light for a lower level room"],
    whatsDateOr: ["Carpet — consider hard flooring for an office chair", "No architectural features — needs furniture to create identity"],
    verdict: "72″+ desk on the long wall facing perpendicular to the window. Gaming + work dual-monitor setup. Daybed or MCM chaise on the opposite wall for crash flexibility. The closet can house a Litter-Robot or extra storage.",
    priority: "In Progress",
    suggestedPalettes: ["Moody Library", "Bold Contrast", "Warm Walnut"],
  },
  ashton_office: {
    summary: "149 sq ft with a window looking out at trees. The room with the yellow/grey bedding in photos. Cozy proportions for a focused lawyer's office with a Murphy bed for guest overflow.",
    whatsGood: ["Wooded window view is calming for focused work", "Good proportions for a desk + Murphy bed combo", "Oak trim consistent with house", "The tree view makes a great video call backdrop if desk faces into room"],
    whatsDateOr: ["Carpet — hard floor better for office chair rolling", "Standard ceiling light needs upgrading for long work sessions"],
    verdict: "Murphy bed on the wall opposite the window. Desk positioned so natural light comes from the side (not behind the screen). Styled bookshelf behind the desk chair for video calls. Good task lighting is non-negotiable for a lawyer's reading sessions.",
    priority: "In Progress",
    suggestedPalettes: ["Scandinavian Light", "Sage & Rust", "Nordic Frost"],
  },
  bonus: {
    summary: "171 sq ft on the lower level. The most flexible room in the house. With both offices defined and the family room as entertainment central, this room can become whatever's missing after you move in.",
    whatsGood: ["Flexible — no predetermined purpose means no constraints", "Good size for a reading room, cat headquarters, or future nursery"],
    whatsDateOr: ["No photos — needs in-person assessment"],
    verdict: "Don't decide yet. Live in the house for 2–3 months and let the need reveal itself. This could be the cat headquarters (consolidate Litter-Robots, cat trees, feeding) or a reading room or a home gym.",
    priority: "Not Started",
    suggestedPalettes: ["Olive & Brass", "Avocado Revival", "Sage & Rust"],
  },
  lower_bath: {
    summary: "The only bathroom serving the entire lower level — two offices, family room, rec room, bonus room, and flex space. Oak vanity, laminate counter, basic tile floor.",
    whatsGood: ["Functional and clean", "Oak vanity matches the house's material language", "Adequate for daily use"],
    whatsDateOr: ["Laminate counter is dated", "Basic tile floor", "Single sink — adequate but not luxurious for a level this size"],
    verdict: "Functional as-is. Low priority. If you finish the flex space for any serious use (rental, studio), you'll eventually need a second bathroom down here. For now: new counter, hardware swap, fresh paint when you get to it.",
    priority: "Not Started",
    suggestedPalettes: [],
  },
  wic_aakesh: {
    summary: "Small closet in Aakesh's office. Could store office supplies, tech gear, or house a Litter-Robot.",
    whatsGood: ["Enclosed space — good for hiding utility items"],
    whatsDateOr: ["11 sq ft is very tight"],
    verdict: "Litter-Robot fits here if you want one near your office. Otherwise, shelving for tech gear and office supplies.",
    priority: "Not Started",
    suggestedPalettes: [],
  },
  wic_ashton: {
    summary: "Slightly larger closet in Ashton's office. Can store case files, office supplies, or function as a mini library nook.",
    whatsGood: ["18 sq ft gives a bit more flexibility than the other closet", "Can fit shelving for legal files and reference materials"],
    whatsDateOr: ["Standard closet — nothing remarkable"],
    verdict: "File storage and office supply closet. Add shelving and good lighting.",
    priority: "Not Started",
    suggestedPalettes: [],
  },
  storage: {
    summary: "623 sq ft wildcard. Larger than most studio apartments. Excluded from official square footage, likely unfinished or partially finished. Highest potential ROI room in the house.",
    whatsGood: ["Massive square footage", "Could become anything: gym, studio, rental unit, FleckTechAI lab", "Separate from main living areas — good for noisy or independent-use purposes"],
    whatsDateOr: ["Condition unknown — may need significant finishing work", "No photos available"],
    verdict: "Don't commit budget here until you've assessed the space in person. If it's partially finished, it could become usable quickly. If it's raw, plan for phased finishing. The rental income potential at 623 sq ft is real if you add a kitchenette and bathroom access.",
    priority: "Not Started",
    suggestedPalettes: [],
  },
};

// Architectural features for 2D layout (positions as % of room dims, type tells renderer how to draw)
// x,y = top-left corner as percentage; w,h = size as percentage
export const ROOM_FEATURES = {
  living: [
    { type: "fireplace", label: "Stone Fireplace", x: 40, y: 0, w: 20, h: 8, color: "#A0958A" },
    { type: "window", label: "Windows", x: 75, y: 0, w: 25, h: 3, color: "#87CEEB55" },
    { type: "window", label: "Floor-to-Ceiling Windows", x: 95, y: 5, w: 5, h: 80, color: "#87CEEB55" },
    { type: "opening", label: "To Foyer", x: 0, y: 70, w: 5, h: 25, color: "#D4C4A8" },
    { type: "opening", label: "To Dining", x: 0, y: 0, w: 5, h: 30, color: "#D4C4A8" },
  ],
  dining: [
    { type: "window", label: "Deck Doors", x: 60, y: 0, w: 35, h: 4, color: "#87CEEB55" },
    { type: "opening", label: "To Living", x: 95, y: 30, w: 5, h: 30, color: "#D4C4A8" },
    { type: "opening", label: "To Kitchen", x: 0, y: 60, w: 5, h: 30, color: "#D4C4A8" },
  ],
  kitchen: [
    { type: "fixture", label: "Island", x: 30, y: 35, w: 35, h: 25, color: "#A0845C88" },
    { type: "window", label: "Window", x: 30, y: 0, w: 30, h: 4, color: "#87CEEB55" },
    { type: "fixture", label: "Counters", x: 0, y: 0, w: 100, h: 12, color: "#D4C4A866" },
    { type: "opening", label: "To Nook", x: 0, y: 70, w: 5, h: 25, color: "#D4C4A8" },
  ],
  breakfast: [
    { type: "window", label: "Deck Door", x: 0, y: 20, w: 5, h: 40, color: "#87CEEB55" },
    { type: "wall_feature", label: "Teal Wall", x: 0, y: 0, w: 5, h: 100, color: "#1A6B6B44" },
  ],
  foyer: [
    { type: "door", label: "Front Door", x: 35, y: 0, w: 25, h: 5, color: "#A0845C" },
    { type: "opening", label: "Stairs Down", x: 60, y: 75, w: 30, h: 25, color: "#D4C4A8" },
    { type: "opening", label: "To Living", x: 95, y: 30, w: 5, h: 35, color: "#D4C4A8" },
  ],
  primary_bed: [
    { type: "window", label: "Patio Door", x: 95, y: 25, w: 5, h: 50, color: "#87CEEB55" },
    { type: "opening", label: "To Bath", x: 0, y: 0, w: 5, h: 25, color: "#D4C4A8" },
    { type: "opening", label: "To Closet", x: 0, y: 75, w: 5, h: 20, color: "#D4C4A8" },
  ],
  family: [
    { type: "fireplace", label: "Stone Fireplace", x: 60, y: 95, w: 18, h: 5, color: "#A0958A" },
    { type: "window", label: "Walkout Doors", x: 95, y: 50, w: 5, h: 40, color: "#87CEEB55" },
    { type: "opening", label: "Stairs Up", x: 0, y: 0, w: 15, h: 8, color: "#D4C4A8" },
    { type: "fixture", label: "Bar Area", x: 10, y: 5, w: 20, h: 10, color: "#A0845C66" },
    { type: "fixture", label: "Curved Railing", x: 0, y: 0, w: 35, h: 4, color: "#A0845C" },
  ],
  aakesh_office: [
    { type: "window", label: "Window", x: 95, y: 30, w: 5, h: 35, color: "#87CEEB55" },
    { type: "opening", label: "Door", x: 0, y: 0, w: 5, h: 20, color: "#D4C4A8" },
    { type: "opening", label: "Closet", x: 0, y: 80, w: 5, h: 15, color: "#D4C4A8" },
  ],
  ashton_office: [
    { type: "window", label: "Window", x: 95, y: 30, w: 5, h: 35, color: "#87CEEB55" },
    { type: "opening", label: "Door", x: 0, y: 0, w: 5, h: 20, color: "#D4C4A8" },
    { type: "opening", label: "Closet", x: 40, y: 95, w: 20, h: 5, color: "#D4C4A8" },
  ],
  deck: [
    { type: "opening", label: "Kitchen Door", x: 0, y: 30, w: 5, h: 25, color: "#D4C4A8" },
    { type: "fixture", label: "Stairs Down", x: 70, y: 90, w: 25, h: 10, color: "#A0845C66" },
    { type: "fixture", label: "Railing", x: 0, y: 95, w: 100, h: 5, color: "#A0845C44" },
  ],
};

export const FURNITURE_PRESETS = {
  living: ["Sofa", "Ball Chair ✦", "Coffee Table", "Media Console / Credenza", "Arc Floor Lamp", "Area Rug (8×10)", "Accent Chairs (pair)"],
  dining: ["Dining Table (84–96″)", "Dining Chairs (set of 8–10)", "Sideboard / Credenza", "Bar Cart", "Statement Pendant Light", "Area Rug"],
  kitchen: ["Counter Stools", "Pendant Lights", "Open Shelf Display"],
  breakfast: ["Round Table (42–48″)", "MCM Chairs (2–4)", "Pendant Light"],
  foyer: ["Console Table", "Large Mirror or Art", "Bench with Storage", "Statement Pendant", "Runner Rug"],
  primary_bed: ["King Platform Bed Frame", "Slim Nightstands (pair, 18–22″)", "Dresser", "Table Lamps", "Area Rug (8×10)", "Blackout Curtains"],
  family: ["Sectional Sofa", "Entertainment Center", "Coffee Table", "Bar Cabinet + Stools", "Accent Chairs", "Floor Lamps", "Area Rugs (zoning)", "Bookshelves"],
  rec: ["TBD — Define Purpose First", "Lounge Seating", "Game Table", "Sound System", "Accent Lighting"],
  aakesh_office: ["L-Desk or 72″+ Desk", "Ergonomic Chair", "Dual Monitor Arms", "MCM Daybed / Convertible Couch", "Bookshelves", "Sound Panels", "Cable Management"],
  ashton_office: ["Murphy Bed (Queen)", "Desk (48–60″)", "Ergonomic Chair", "Monitor Arm", "Bookshelf (video backdrop)", "File Storage", "Desk + Task Lamp"],
  deck: ["Blackstone Griddle (36″)", "Prep Cart / Table", "Outdoor Dining Set", "Tool Storage"],
  storage: ["TBD — Assess In Person First"],
};

// First 30 Days action plan
export const ACTION_PLAN = [
  { week: "Move-In Week", items: [
    { task: "Measure every room — confirm dimensions against floor plan", room: null, priority: "high" },
    { task: "Order closet system for primary walk-in (Elfa, PAX, or custom)", room: "primary_wic", priority: "high" },
    { task: "Assess carpet condition — get flooring quotes for main level", room: null, priority: "high" },
    { task: "Decide Litter-Robot placement — measure laundry room and closets", room: "laundry", priority: "high" },
    { task: "Set up temporary desk in Aakesh's office — you need to work", room: "aakesh_office", priority: "high" },
    { task: "Set up temporary desk in Ashton's office", room: "ashton_office", priority: "high" },
  ]},
  { week: "Week 2", items: [
    { task: "Strip half-bath wallpaper, repaint, replace vertical blinds", room: null, priority: "medium" },
    { task: "Swap kitchen cabinet hardware — brass or matte black pulls", room: "kitchen", priority: "medium" },
    { task: "Order flooring samples — hardwood to match existing kitchen floors", room: null, priority: "high" },
    { task: "MCM house numbers + exterior light fixture for curb appeal", room: "porch", priority: "low" },
    { task: "Assess deck condition — check for rot on railings and stairs", room: "deck", priority: "medium" },
  ]},
  { week: "Week 3–4", items: [
    { task: "Finalize dining table selection — need dimensions to plan room", room: "dining", priority: "high" },
    { task: "Shop for living room furniture — sofa, coffee table to complement ball chair and fireplace", room: "living", priority: "high" },
    { task: "Order Murphy bed for Ashton's office", room: "ashton_office", priority: "medium" },
    { task: "Research Blackstone griddle setup — 28″ vs 36″, prep cart options", room: "deck", priority: "medium" },
    { task: "Assess flex space condition in person — finished, partial, or raw?", room: "storage", priority: "low" },
    { task: "Order king platform bed frame if needed", room: "primary_bed", priority: "high" },
  ]},
  { week: "Month 2+", items: [
    { task: "Flooring installation — main level carpet removal + hardwood", room: null, priority: "high" },
    { task: "Primary bath — swap ceiling fixture, decide on wallpaper", room: "primary_bath", priority: "low" },
    { task: "Family room zoning — arrange furniture around fireplace + bar area", room: "family", priority: "medium" },
    { task: "Bonus room — live with the house first, then decide purpose", room: "bonus", priority: "low" },
    { task: "Rec room — define purpose based on what you're missing", room: "rec", priority: "low" },
  ]},
];

export const MCM_PALETTES = {
  "Warm Walnut": { primary: "#5C3D2E", secondary: "#D4A76A", accent: "#C75B12", bg: "#FAF3EB", muted: "#E8D5C4" },
  "Teak & Mustard": { primary: "#7A5C1F", secondary: "#D4A017", accent: "#B8860B", bg: "#FFFBE6", muted: "#F0E4B8" },
  "Avocado Revival": { primary: "#4A6234", secondary: "#8FBC8F", accent: "#DAA520", bg: "#F5F7F0", muted: "#D4E0C8" },
  "Desert Modern": { primary: "#A07850", secondary: "#E8D5B7", accent: "#8B4513", bg: "#FFF8F0", muted: "#ECDCC8" },
  "Atomic Ranch": { primary: "#C4622D", secondary: "#FF8C00", accent: "#006D6F", bg: "#FFF5EE", muted: "#F0D8C8" },
  "Scandinavian Light": { primary: "#8A7B6B", secondary: "#E8DDD0", accent: "#4A6741", bg: "#FAFAF7", muted: "#E8E2D8" },
  "Bold Contrast": { primary: "#1A1A1A", secondary: "#F5F5DC", accent: "#D4380D", bg: "#FFFFFF", muted: "#E8E8E0" },
  "Coastal Teak": { primary: "#2E7D7D", secondary: "#A0D2DB", accent: "#C4874D", bg: "#F0FAFA", muted: "#C8E4E8" },
  "Palm Springs": { primary: "#D4637A", secondary: "#F5CCD3", accent: "#2D8B72", bg: "#FFF5F6", muted: "#F0D8DC" },
  "Burnt Sienna": { primary: "#A0522D", secondary: "#DEB887", accent: "#2F4F4F", bg: "#FFF8F0", muted: "#E4CDB8" },
  "Harvest Gold": { primary: "#B8860B", secondary: "#F0DC82", accent: "#704214", bg: "#FFFDE8", muted: "#F0E4B0" },
  "Moody Library": { primary: "#2C3E50", secondary: "#8B7355", accent: "#C0392B", bg: "#F4F1EC", muted: "#D0C8BC" },
  "Olive & Brass": { primary: "#556B2F", secondary: "#C8B560", accent: "#8B6914", bg: "#F7F6F0", muted: "#D8D4B8" },
  "Terracotta Sun": { primary: "#CC5533", secondary: "#E8B88A", accent: "#1B5E4B", bg: "#FFF6F0", muted: "#F0D4C0" },
  "Nordic Frost": { primary: "#5B7B8A", secondary: "#C4D4DC", accent: "#A0522D", bg: "#F5F8FA", muted: "#D4DEE4" },
  "Chocolate & Cream": { primary: "#3E2723", secondary: "#EFEBE9", accent: "#BF8040", bg: "#FEFCFA", muted: "#E0D4C8" },
  "Sage & Rust": { primary: "#7A8B6F", secondary: "#D4CCBB", accent: "#B7532A", bg: "#F6F5F0", muted: "#D0D4C4" },
  "Sunset Strip": { primary: "#D35400", secondary: "#F5B041", accent: "#1A5276", bg: "#FFF8F2", muted: "#F0D8B8" },
  "Eames Era": { primary: "#C0392B", secondary: "#F8F4E8", accent: "#1A1A1A", bg: "#FDFCF8", muted: "#E8E0D0" },
  "Malibu Dusk": { primary: "#6C5B7B", secondary: "#C9B8D4", accent: "#D4874D", bg: "#F8F5FA", muted: "#DCD0E4" },
};

export const FURNITURE_PIECES = {
  "King Bed":{w:76,h:80,color:"#8B7355",label:"King"},"Queen Bed":{w:60,h:80,color:"#8B7355",label:"Queen"},
  "Murphy Bed (Q)":{w:64,h:84,color:"#8B7355",label:"Murphy"},"Nightstand":{w:20,h:18,color:"#A0845C",label:"NS"},
  "Dresser":{w:60,h:18,color:"#A0845C",label:"Dresser"},'Sofa (84")':{w:84,h:36,color:"#6B7B6B",label:"Sofa"},
  "Sectional L":{w:108,h:84,color:"#6B7B6B",label:"Sectional"},"Ball Chair":{w:42,h:42,color:"#C75B12",label:"Ball"},
  "Coffee Table":{w:48,h:24,color:"#A0845C",label:"Coffee"},'Dining Table (96")':{w:96,h:42,color:"#7A5C1F",label:"Dining"},
  "Dining Chair":{w:20,h:20,color:"#8B7355",label:"Ch"},'Credenza (72")':{w:72,h:18,color:"#A0845C",label:"Credenza"},
  'L-Desk (72")':{w:72,h:30,color:"#5C5C5C",label:"L-Desk"},'Desk (60")':{w:60,h:28,color:"#5C5C5C",label:"Desk"},
  'Desk (48")':{w:48,h:24,color:"#5C5C5C",label:"Desk"},"Office Chair":{w:24,h:24,color:"#444",label:"Chair"},
  "Bookshelf":{w:36,h:12,color:"#A0845C",label:"Books"},"Bar Cart":{w:30,h:18,color:"#B8860B",label:"Bar"},
  "Bar Cabinet":{w:48,h:20,color:"#5C3D2E",label:"Bar Cab"},"Bar Stool":{w:16,h:16,color:"#8B7355",label:"Stool"},
  "Floor Lamp":{w:12,h:12,color:"#888",label:"Lamp"},"Area Rug (8×10)":{w:96,h:120,color:"rgba(160,132,92,0.2)",label:"Rug"},
  "Cat Tree":{w:24,h:24,color:"#8FBC8F",label:"Cat"},"Litter-Robot":{w:26,h:28,color:"#A09080",label:"LR"},
  "Accent Chair":{w:30,h:30,color:"#6B7B6B",label:"Accent"},"Daybed":{w:78,h:36,color:"#8B7355",label:"Daybed"},
  "MCM Chaise":{w:60,h:28,color:"#6B7B6B",label:"Chaise"},"Entertainment Center":{w:72,h:20,color:"#5C3D2E",label:"Media"},
  'Blackstone 36"':{w:42,h:22,color:"#333",label:"Griddle"},"Prep Table":{w:36,h:24,color:"#888",label:"Prep"},
  "Console Table":{w:48,h:14,color:"#A0845C",label:"Console"},"Bench":{w:48,h:16,color:"#8B7355",label:"Bench"},
  "Arc Lamp":{w:24,h:24,color:"#888",label:"Arc"},
};

export const DESIGN_THEMES = ["Classic MCM","MCM + Boho","MCM + Industrial","MCM + Japandi","MCM + Maximalist","MCM + Minimalist","MCM + Scandinavian","Retro Atomic"];
export const PRIORITIES = ["Not Started","Planning","In Progress","Complete"];
export const PRIORITY_COLORS = {"Not Started":"#A09080","Planning":"#C4922A","In Progress":"#C4622D","Complete":"#4A6234"};
